<?php
namespace app\api\controller;

use app\base\controller\Base;
use think\Request;
use think\Response;

class Controller extends Base
{
    const JSON_SUCCESS_STATUS = 1;
    const JSON_ERROR_STATUS = 0;
//    protected function _initialize()
//    {
//        $request = Request::instance();
//        if(!$request->header('token'))
//        {
//            $this->OAuth = config('wechatapi.OAuth')['official_account']['api'];
//            $appId = config('we_chat.AppID');
//            $redirectUri = $request->domain().$request->url();
//            $url = sprintf($this->OAuth,$appId,$redirectUri);
//            $this->redirect($url);
//        }
//        parent::_initialize(); // TODO: Change the autogenerated stub
//    }
    protected function renderSuccess($data=[], $code=self::JSON_SUCCESS_STATUS, $msg='success')
    {
        if (empty($data)){
            $code=10000;
            $msg= '没有数据';
        }
        return $this->renderJson($data,$code,$msg);
        // TODO: Implement renderSuccess() method.
    }
    protected function renderError($data=[], $code=self::JSON_ERROR_STATUS, $msg='error')
    {
        return $this->renderJson($data,$code,$msg);
        // TODO: Implement renderError() method.
    }
    private function renderJson($data, $code, $msg)
    {
        return compact('data','code','msg');
    }
    protected function getUser()
    {

    }
}